name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'Fluffy9'
        reponame: 'HarbergerTaxUI'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
    - id: IPFS
      uses: aquiladev/ipfs-action@v0.3.1
      with:
        path: ./dist
        service: filebase
        pinName: 'ipfs-action'
        filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
        filebaseKey: ${{ secrets.FILEBASE_KEY }}
        filebaseSecret: ${{ secrets.FILEBASE_SECRET }}
